buildscript {
    repositories {
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    }
    dependencies {
        classpath group: "net.minecraftforge.gradle", name: "ForgeGradle", version: "6.0.+", changing: true
        classpath group: "org.spongepowered", name: "mixingradle", version: "0.7-SNAPSHOT"
    }
}

apply plugin: "net.minecraftforge.gradle"
apply plugin: "eclipse"
apply plugin: "maven-publish"
apply plugin: "org.spongepowered.mixin"

mixin {
    add sourceSets.main, "${project.modId}.refmap.json"
}

version = "${project.minecraft}-${project.modVersion}"
group = "com.davigj"
archivesBaseName = project.modId

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: "official", version: project.minecraft
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")
    runs {
        client {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                whiffowisp {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            arg "-mixin.config=" + project.modId + ".mixins.json"
            mods {
                whiffowisp {
                    source sourceSets.main
                }
            }
        }
        data {
            workingDirectory project.file("run")
            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            property "forge.logging.console.level", "debug"
            property "mixin.env.remapRefMap", "true"
            property "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"
            property "blueprint.indev", "true"
            args "--mod", project.modId, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources"), "--existing-mod", "blueprint", "--existing-mod", "buzzier_bees"
            mods {
                whiffowisp {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft}-${project.forge}"
    implementation fg.deobf("com.teamabnormals:blueprint:${project.minecraft}-${project.blueprint}")
    implementation fg.deobf("maven.modrinth:statement:m8DpH9VB")

    compileOnly fg.deobf("maven.modrinth:buzzier-bees:PyMRj9VM")
    compileOnly fg.deobf("maven.modrinth:supplementaries:KgkjZ2z3")
    compileOnly fg.deobf("maven.modrinth:amendments:73W8UHX3")
    compileOnly fg.deobf("maven.modrinth:jadens-nether-expansion:mWogGDsB")
    compileOnly fg.deobf("maven.modrinth:elysium-api:SqTYKsC6")
    compileOnly fg.deobf("maven.modrinth:doom-gloom:wBhe6O8T")
    compileOnly fg.deobf("maven.modrinth:alexs-caves:lC8HHXOF")
    compileOnly fg.deobf("maven.modrinth:citadel:lTAAe4sZ")

    runtimeOnly fg.deobf("maven.modrinth:autumnity:F0pPtIPH")
    runtimeOnly fg.deobf("maven.modrinth:caverns-and-chasms:fsal1BlK")
    runtimeOnly fg.deobf("maven.modrinth:upgrade-aquatic:nWAYgQaF")
    runtimeOnly fg.deobf("maven.modrinth:environmental:DA9khYQj")
    runtimeOnly fg.deobf("maven.modrinth:buzzier-bees:PyMRj9VM")
    runtimeOnly fg.deobf("maven.modrinth:atmospheric:B9fN8ZSq")
    runtimeOnly fg.deobf("maven.modrinth:spelunkery:jW8j0zdc")
    runtimeOnly fg.deobf("maven.modrinth:alexs-caves:lC8HHXOF")
    runtimeOnly fg.deobf("maven.modrinth:citadel:lTAAe4sZ")

    runtimeOnly fg.deobf("maven.modrinth:farmers-delight:8rPF1pFi")

    runtimeOnly fg.deobf("maven.modrinth:jadens-nether-expansion:mWogGDsB")
    runtimeOnly fg.deobf("maven.modrinth:elysium-api:SqTYKsC6")
    runtimeOnly fg.deobf("maven.modrinth:doom-gloom:wBhe6O8T")

    runtimeOnly fg.deobf("maven.modrinth:supplementaries:KgkjZ2z3")
    runtimeOnly fg.deobf("maven.modrinth:amendments:73W8UHX3")
    runtimeOnly fg.deobf("maven.modrinth:moonlight:lrpPgviq")

//    runtimeOnly fg.deobf("curse.maven:the-twilight-forest-227639:5468648")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.0")) {
        jarJar.ranged(it, "[0.4.0,)")
    }

    compileOnly fg.deobf("mezz.jei:jei-${project.minecraft}-common-api:${project.jei}")
    compileOnly fg.deobf("mezz.jei:jei-${project.minecraft}-forge-api:${project.jei}")
    runtimeOnly fg.deobf("mezz.jei:jei-${project.minecraft}-forge:${project.jei}")

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
}

repositories {
    maven { url "https://maven.teamabnormals.com" }
    maven { url "https://dvs1.progwml6.com/files/maven/" }
    maven { url "https://modmaven.k-4u.nl" }
    maven { url "https://www.cursemaven.com" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository) // Only add this if you're using ForgeGradle, otherwise remove this line
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : project.modName,
                "Specification-Vendor"    : "DavigJ",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.modName,
                "Implementation-Version"  : project.modVersion,
                "Implementation-Vendor"   : "DavigJ",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs"            : project.modId + ".mixins.json"
        ])
    }
}