modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/whiffowisp/issues"
license = "MIT License"

[[mods]]
modId = "whiffowisp"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:candle"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Art credits go to Tutta, SuperMightByte, and Ghost"
displayURL = "https://modrinth.com/mod/whiffowisp"
displayName = "Whiff O' Wisp"
description = '''
    Adds scented candles, as well as the ability to trim normal candles such that they do not produce smoke particles.
    '''

[[dependencies.whiffowisp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.whiffowisp]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.whiffowisp]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.whiffowisp]]
modId = "statement"
mandatory = true
versionRange = "[4.2.7,)"
ordering = "AFTER"
side = "BOTH"